### ISSUE TITLE
Spam errors in the build of mods

### ISSUE THREAD

**Issue by Paradox75831004** [Shaosil/LethalCompanyMods-FlashlightFix#3]
The mod build code is 018d446d-706a-9c50-1c43-99f2f5429daa

![image](https://github.com/Shaosil/LethalCompanyMods-FlashlightFix/assets/72872478/fdeef3a8-2afc-4d7c-a3f4-43913df47607)

**Comment by milleroski** [comment]
I've noticed the same error. This seems to be due to the new keybind function that you can set in the config. Whenever it's set to "None", which is the default value, it starts printing this error. A temporary workaround is just to bind it to some random key that you're not gonna use, but this should be fixed anyway.

**Comment by Shaosil** [comment]
Fixed in v1.0.7, going live soon
